apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector:
    app: gop-fileserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    ### 
    # add NodePort