apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector:
    run: kekyll-pod
  ports:
    - port: 8080
      targetPort: 4000
      nodePort: 30097